# Generated by Django 4.0.5 on 2022-06-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
